# ./EKS/Deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft
  template:
    metadata:
      labels:
        app: ft
    spec:
      containers:
        - name: ft
          image: AWS_ECR_URI
          ports:
            - containerPort: 5000
          imagePullPolicy: Always